// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/load_balancers.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/mocks/lb_service.go --package=mocks --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/load_balancers.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockLoadBalancersService is a mock of LoadBalancersService interface.
type MockLoadBalancersService struct {
	ctrl     *gomock.Controller
	recorder *MockLoadBalancersServiceMockRecorder
}

// MockLoadBalancersServiceMockRecorder is the mock recorder for MockLoadBalancersService.
type MockLoadBalancersServiceMockRecorder struct {
	mock *MockLoadBalancersService
}

// NewMockLoadBalancersService creates a new mock instance.
func NewMockLoadBalancersService(ctrl *gomock.Controller) *MockLoadBalancersService {
	mock := &MockLoadBalancersService{ctrl: ctrl}
	mock.recorder = &MockLoadBalancersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadBalancersService) EXPECT() *MockLoadBalancersServiceMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockLoadBalancersService) Collection() serverscom.Collection[serverscom.LoadBalancer] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.LoadBalancer])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockLoadBalancersServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockLoadBalancersService)(nil).Collection))
}

// CreateL4LoadBalancer mocks base method.
func (m *MockLoadBalancersService) CreateL4LoadBalancer(ctx context.Context, input serverscom.L4LoadBalancerCreateInput) (*serverscom.L4LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateL4LoadBalancer", ctx, input)
	ret0, _ := ret[0].(*serverscom.L4LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateL4LoadBalancer indicates an expected call of CreateL4LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) CreateL4LoadBalancer(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateL4LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).CreateL4LoadBalancer), ctx, input)
}

// CreateL7LoadBalancer mocks base method.
func (m *MockLoadBalancersService) CreateL7LoadBalancer(ctx context.Context, input serverscom.L7LoadBalancerCreateInput) (*serverscom.L7LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateL7LoadBalancer", ctx, input)
	ret0, _ := ret[0].(*serverscom.L7LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateL7LoadBalancer indicates an expected call of CreateL7LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) CreateL7LoadBalancer(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateL7LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).CreateL7LoadBalancer), ctx, input)
}

// DeleteL4LoadBalancer mocks base method.
func (m *MockLoadBalancersService) DeleteL4LoadBalancer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteL4LoadBalancer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteL4LoadBalancer indicates an expected call of DeleteL4LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) DeleteL4LoadBalancer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteL4LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).DeleteL4LoadBalancer), ctx, id)
}

// DeleteL7LoadBalancer mocks base method.
func (m *MockLoadBalancersService) DeleteL7LoadBalancer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteL7LoadBalancer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteL7LoadBalancer indicates an expected call of DeleteL7LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) DeleteL7LoadBalancer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteL7LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).DeleteL7LoadBalancer), ctx, id)
}

// GetL4LoadBalancer mocks base method.
func (m *MockLoadBalancersService) GetL4LoadBalancer(ctx context.Context, id string) (*serverscom.L4LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetL4LoadBalancer", ctx, id)
	ret0, _ := ret[0].(*serverscom.L4LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetL4LoadBalancer indicates an expected call of GetL4LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) GetL4LoadBalancer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetL4LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).GetL4LoadBalancer), ctx, id)
}

// GetL7LoadBalancer mocks base method.
func (m *MockLoadBalancersService) GetL7LoadBalancer(ctx context.Context, id string) (*serverscom.L7LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetL7LoadBalancer", ctx, id)
	ret0, _ := ret[0].(*serverscom.L7LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetL7LoadBalancer indicates an expected call of GetL7LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) GetL7LoadBalancer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetL7LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).GetL7LoadBalancer), ctx, id)
}

// UpdateL4LoadBalancer mocks base method.
func (m *MockLoadBalancersService) UpdateL4LoadBalancer(ctx context.Context, id string, input serverscom.L4LoadBalancerUpdateInput) (*serverscom.L4LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateL4LoadBalancer", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.L4LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateL4LoadBalancer indicates an expected call of UpdateL4LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) UpdateL4LoadBalancer(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateL4LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).UpdateL4LoadBalancer), ctx, id, input)
}

// UpdateL7LoadBalancer mocks base method.
func (m *MockLoadBalancersService) UpdateL7LoadBalancer(ctx context.Context, id string, input serverscom.L7LoadBalancerUpdateInput) (*serverscom.L7LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateL7LoadBalancer", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.L7LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateL7LoadBalancer indicates an expected call of UpdateL7LoadBalancer.
func (mr *MockLoadBalancersServiceMockRecorder) UpdateL7LoadBalancer(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateL7LoadBalancer", reflect.TypeOf((*MockLoadBalancersService)(nil).UpdateL7LoadBalancer), ctx, id, input)
}
